stages:
  - build
  - test

Compile:
  stage: build
  tags:
    - typescript
  script:
    - tsc index.ts
    
Test:
  stage: test
  tags:
    - typescript
    - tslint
  script:
    - tslint -c tslint.json index.ts
