version: '2'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    ports:
        - '80:80'

runner-ts:
    build: runner-ts/. # Dockerfile in runner-te folder

  runner-deploy:
    build: runner-deploy/.
    volumes:
      - staging:/www-staging
      - production:/www-production

  staging:
    image: 'nginx'
    ports:
      - '8081:80'
    volumes:
      - staging:/usr/share/nginx/html

  production:
    image: 'nginx'
    ports:
      - '8082:80'
    volumes:
      - production:/usr/share/nginx/html

volumes:
  staging:
  production:
